apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3madmin-web
  namespace: colis-dev
  labels:
    app: c3madmin-web
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3madmin-web
  template:
    metadata:
      labels:
        app: c3madmin-web
    spec:
      containers:
        - name: c3madmin-web #1st container
          image: tidusant/c3madmin_web:latest #Dockerhub image
          ports:
            - containerPort: 80 #Exposes the port 8080 of the container
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://test.duyhf.com:8081/
            - name: NEXT_PUBLIC_DEBUG 
              value: "false"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          livenessProbe:
            httpGet:
              path: /
              port: 80
              # httpHeaders:
              # - name: Custom-Header
              #   value: Awesome test test
            initialDelaySeconds: 3
            periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: c3madmin-web-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3madmin-web
  ports:
    - name: c3madmin-web-port
      protocol: TCP
      port: 80
      nodePort: 30080 #must be between 30000 - 32767
  